POST http://localhost:3333/gpu
Content-Type: application/json

{
    "marca": "gpu: Nvidia rtx 3080",
    "fabricante": "fabricante: Gigabyte",
    "preço": "R$3000"
}

###

GET http://localhost:3333/gpu

###

GET http://localhost:3333/gpu?search=IFMS

###

PUT http://localhost:3333/gpus/72d17ad7-d9e1-4887-978f-c756b99c7fd3
Content-Type: application/json

{
    "marca": "gpu: Nvidia rtx 4070",
    "fabricante": "Fabricante Galax",
    "preço": "R$5000"
}

###

DELETE http://localhost:3333/gpus/cb28aef1-39d8-4fb7-8a88-be2f569cef76